"""
Direct RPC Server (for demo_front chat)
=====================================
Single-port 19090 FastAPI server providing:
  - 3 partner roles (search/analysis/writing) for multi-agent orchestration
  - /chat endpoint for normal conversational LLM access
All LLM calls go to DeepSeek (key from .env), bypassing RabbitMQ GroupSession.
"""
import os
import json
import logging
import time
from typing import Any
import httpx
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

# ----- LLM config (from .env) -----
LLM_API_KEY = os.getenv("LLM_API_KEY", "")
LLM_API_URL = os.getenv("LLM_API_URL", "https://api.deepseek.com/v1/chat/completions")
LLM_MODEL = os.getenv("LLM_MODEL", "deepseek-chat")
LLM_MAX_TOKENS_DEFAULT = int(os.getenv("LLM_MAX_TOKENS", "4096"))
EVENT_CENTER_URL = os.getenv(
    "EVENT_CENTER_URL", "http://127.0.0.1:8001/api/events/publish"
)
EVENT_CENTER_TOKEN = os.getenv("EVENT_CENTER_TOKEN", "local-dev-token")

# ----- 3 role system prompts (replicated from partner main.py) -----
SYSTEM_PROMPTS = {
    "search": (
        "You are a professional academic literature search & screening expert. "
        "Given a research topic, generate a realistic literature list: 15-20 papers, "
        "covering multiple research directions, with real-looking titles, authors, "
        "and venue names. Each entry: number/author/title/venue/year/direction/relevance(high/mid/low). "
        "End with: this is Agent1's standardized literature list, ready for Agent2."
    ),
    "analysis": (
        "You are a senior academic literature analyst. Deeply analyze the literature list from Agent1. "
        "Output: (1) Per-paper core view decomposition (table: paper|method|contribution|limitation|rating). "
        "(2) Research evolution timeline. (3) Major school comparison (table). "
        "(4) Research gaps and future directions. "
        "End with: this is Agent2's analysis draft, ready for Agent3."
    ),
    "writing": (
        "You are a senior academic review writer. Based on Agent2's analysis, write a full academic review. "
        "Structure: title/abstract(200-300 words)/keywords/introduction/main sections(>=3)/conclusion/references. "
        "Markdown format, citations as [1][2]. Objective academic tone, brief summary at each section end. "
        "End with: this paper was auto-generated by multi-agent collaboration (Agent1 search -> Agent2 analyze -> Agent3 write)."
    ),
}

ROLE_MAX_TOKENS = {
    "search": 8192,
    "analysis": 8192,
    "writing": LLM_MAX_TOKENS_DEFAULT,
}

# ----- Plain chat system prompt -----
CHAT_SYSTEM_PROMPT = (
    "You are Marvis, the AI assistant for an agent application store. "
    "You help users: answer questions, explain concepts, write text, translate, polish, generate creative content. "
    "Reply friendly, concise, well-structured; Chinese preferred; answer directly when no tools are needed; "
    "if uncertain about a fact, say so honestly rather than fabricate."
)

def build_user_prompt(role: str, task: str, upstream: str) -> str:
    if role == "search":
        return (
            f"Research topic: {task}\n\n"
            "Generate 15-20 standardized literature entries, grouped by research direction. "
            "Each entry must include: number/author/title/venue/year/direction/relevance(high/mid/low)."
        )
    if role == "analysis":
        if not upstream:
            upstream = task
        return (
            "Deeply analyze the following literature list, output view decomposition and research evolution draft.\n\n"
            f"## Literature list\n\n{upstream}"
        )
    if role == "writing":
        if not upstream:
            upstream = task
        return (
            "Write a full academic review (body >= 2000 words) based on the following analysis.\n\n"
            f"## Analysis report\n\n{upstream}\n\n"
            "Strict structure:\n"
            "1. Title\n2. Abstract (200-300 words)\n3. Keywords\n4. Introduction\n"
            "5. Main sections (>= 3)\n6. Conclusion\n7. References"
        )
    return task or upstream or ""

app = FastAPI(title="Direct RPC Server", version="1.0.0")
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
log = logging.getLogger("direct_rpc")


async def publish_runtime_event(
    *,
    event_type: str,
    level: str,
    title: str,
    message: str,
    extra: dict[str, Any] | None = None,
) -> None:
    if not EVENT_CENTER_URL or not EVENT_CENTER_TOKEN:
        return
    payload = {
        "source": "direct-rpc",
        "type": event_type,
        "level": level,
        "title": title,
        "message": message,
        "extra": {"service": "direct-rpc", **(extra or {})},
    }
    try:
        async with httpx.AsyncClient(timeout=2.0) as client:
            await client.post(
                EVENT_CENTER_URL,
                json=payload,
                headers={"Authorization": f"Bearer {EVENT_CENTER_TOKEN}"},
            )
    except Exception as exc:
        log.debug("failed to publish direct-rpc runtime event: %s", exc)


class DirectRpcRequest(BaseModel):
    role: str = Field(..., description="search | analysis | writing")
    task: str = Field(default="", description="Original user task")
    upstream: str = Field(default="", description="Upstream role output")


class ChatRequest(BaseModel):
    message: str = Field(..., description="User message")
    history: list = Field(default_factory=list, description="Optional: history [{role, content}]")
    system: str = Field(default="", description="Optional: custom system prompt")


@app.get("/health")
async def health():
    return {
        "status": "ok" if LLM_API_KEY else "no_llm_key",
        "llm_model": LLM_MODEL,
        "llm_api_url": LLM_API_URL,
        "supported_roles": list(SYSTEM_PROMPTS.keys()),
        "endpoints": ["/health", "/direct_rpc", "/chat"],
    }


@app.post("/direct_rpc")
async def direct_rpc(req: DirectRpcRequest):
    started = time.perf_counter()
    role = req.role.strip().lower()
    try:
        if role not in SYSTEM_PROMPTS:
            raise HTTPException(400, f"unknown role: {role!r}. must be one of {list(SYSTEM_PROMPTS.keys())}")
        if not LLM_API_KEY:
            raise HTTPException(503, "LLM_API_KEY not set in environment")
        sys_prompt = SYSTEM_PROMPTS[role]
        user_prompt = build_user_prompt(role, req.task, req.upstream)
        if not user_prompt.strip():
            raise HTTPException(400, "task and upstream are both empty")
        log.info("direct_rpc role=%s task_len=%d upstream_len=%d", role, len(req.task), len(req.upstream))
        payload = {
            "model": LLM_MODEL,
            "messages": [
                {"role": "system", "content": sys_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "stream": False,
            "max_tokens": ROLE_MAX_TOKENS.get(role, LLM_MAX_TOKENS_DEFAULT),
            "temperature": 0.7,
        }
        headers = {
            "Authorization": f"Bearer {LLM_API_KEY}",
            "Content-Type": "application/json",
            "User-Agent": "demo-front-direct-rpc/1.0",
        }
        try:
            async with httpx.AsyncClient(timeout=180.0) as client_http:
                r = await client_http.post(LLM_API_URL, headers=headers, json=payload)
                if r.status_code != 200:
                    log.error("LLM returned %d: %s", r.status_code, r.text[:300])
                    raise HTTPException(502, f"LLM upstream HTTP {r.status_code}: {r.text[:200]}")
                j = r.json()
        except httpx.TimeoutException:
            raise HTTPException(504, "LLM upstream timeout")
        except httpx.HTTPError as e:
            raise HTTPException(502, f"LLM upstream error: {e}")
        try:
            content = j["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError):
            log.error("LLM response malformed: %s", json.dumps(j)[:300])
            raise HTTPException(502, "LLM response malformed (no choices[0].message.content)")
        usage = j.get("usage", {})
        duration_ms = round((time.perf_counter() - started) * 1000)
        log.info("direct_rpc done role=%s output_len=%d tokens=%s", role, len(content), usage)
        await publish_runtime_event(
            event_type="direct_rpc.role.completed",
            level="success",
            title="Direct RPC 角色调用完成",
            message=f"Direct RPC role={role} 完成，输出 {len(content)} 字符。",
            extra={
                "stage": "direct-rpc",
                "path": "/direct_rpc",
                "role": role,
                "model": LLM_MODEL,
                "durationMs": duration_ms,
                "outputLength": len(content),
                "usage": usage,
            },
        )
        return {"result": content, "role": role, "model": LLM_MODEL, "usage": usage}
    except HTTPException as exc:
        await publish_runtime_event(
            event_type="direct_rpc.role.failed",
            level="error",
            title="Direct RPC 角色调用失败",
            message=f"Direct RPC role={role or '-'} 失败：{exc.detail}",
            extra={
                "stage": "direct-rpc",
                "path": "/direct_rpc",
                "role": role,
                "statusCode": exc.status_code,
                "durationMs": round((time.perf_counter() - started) * 1000),
            },
        )
        raise


@app.post("/chat")
async def chat_endpoint(req: ChatRequest):
    """Plain chat endpoint — for chat UI to get a direct LLM answer."""
    started = time.perf_counter()
    try:
        if not LLM_API_KEY:
            raise HTTPException(503, "LLM_API_KEY not set in environment")
        if not req.message or not req.message.strip():
            raise HTTPException(400, "message is empty")
        sys_prompt = req.system.strip() or CHAT_SYSTEM_PROMPT
        messages = [{"role": "system", "content": sys_prompt}]
        for h in (req.history or [])[-20:]:
            if isinstance(h, dict) and h.get("role") in ("user", "assistant") and h.get("content"):
                messages.append({"role": h["role"], "content": str(h["content"])})
        messages.append({"role": "user", "content": req.message})
        log.info("chat_endpoint msg_len=%d history=%d", len(req.message), len(req.history or []))
        payload = {
            "model": LLM_MODEL,
            "messages": messages,
            "stream": False,
            "max_tokens": 2048,
            "temperature": 0.7,
        }
        headers = {
            "Authorization": f"Bearer {LLM_API_KEY}",
            "Content-Type": "application/json",
            "User-Agent": "demo-front-chat/1.0",
        }
        try:
            async with httpx.AsyncClient(timeout=60.0) as client_http:
                r = await client_http.post(LLM_API_URL, headers=headers, json=payload)
                if r.status_code != 200:
                    log.error("LLM chat returned %d: %s", r.status_code, r.text[:300])
                    raise HTTPException(502, f"LLM upstream HTTP {r.status_code}: {r.text[:200]}")
                j = r.json()
        except httpx.TimeoutException:
            raise HTTPException(504, "LLM upstream timeout")
        except httpx.HTTPError as e:
            raise HTTPException(502, f"LLM upstream error: {e}")
        try:
            content = j["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError):
            log.error("LLM chat response malformed: %s", json.dumps(j)[:300])
            raise HTTPException(502, "LLM response malformed")
        usage = j.get("usage", {})
        duration_ms = round((time.perf_counter() - started) * 1000)
        log.info("chat_endpoint done reply_len=%d tokens=%s", len(content), usage)
        await publish_runtime_event(
            event_type="direct_rpc.chat.completed",
            level="success",
            title="Direct RPC 聊天完成",
            message=f"Direct RPC chat 完成，回复 {len(content)} 字符。",
            extra={
                "stage": "chat",
                "path": "/chat",
                "model": LLM_MODEL,
                "durationMs": duration_ms,
                "replyLength": len(content),
                "usage": usage,
            },
        )
        return {"result": content, "model": LLM_MODEL, "usage": usage}
    except HTTPException as exc:
        await publish_runtime_event(
            event_type="direct_rpc.chat.failed",
            level="error",
            title="Direct RPC 聊天失败",
            message=f"Direct RPC chat 失败：{exc.detail}",
            extra={
                "stage": "chat",
                "path": "/chat",
                "statusCode": exc.status_code,
                "durationMs": round((time.perf_counter() - started) * 1000),
            },
        )
        raise


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("DIRECT_RPC_PORT", "19090"))
    log.info("Starting direct_rpc_server on 0.0.0.0:%d (LLM=%s)", port, LLM_MODEL)
    if not LLM_API_KEY:
        log.warning("LLM_API_KEY is empty! set it before calling /direct_rpc or /chat")
    uvicorn.run(app, host="0.0.0.0", port=port, log_level="info")
