"""replace_acp_url_with_acp_spec_and_hash

Revision ID: c34ab1646dce
Revises: c26a582dbc62
Create Date: 2025-05-29 10:45:43.152317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34ab1646dce'
down_revision: Union[str, None] = 'c26a582dbc62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('acp_spec', sa.Text(), nullable=True))
    op.add_column('agent', sa.Column('acp_spec_hash', sa.String(length=256), nullable=True))
    op.drop_column('agent', 'acp_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('acp_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('agent', 'acp_spec_hash')
    op.drop_column('agent', 'acp_spec')
    # ### end Alembic commands ###
