"""init

Revision ID: 8b47307376f5
Revises:
Create Date: 2025-04-26 12:52:46.675725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8b47307376f5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_role",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "name", sa.Enum("CLIENT", "STAFF", "ADMIN", name="roletype"), nullable=False
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_role_id"), "account_role", ["id"], unique=False)
    op.create_index(
        op.f("ix_account_role_name"), "account_role", ["name"], unique=False
    )
    op.create_table(
        "account_user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("avatar", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("org_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("org_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("org_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_user_email"), "account_user", ["email"], unique=True
    )
    op.create_index(op.f("ix_account_user_id"), "account_user", ["id"], unique=False)
    op.create_index(
        op.f("ix_account_user_phone"), "account_user", ["phone"], unique=True
    )
    op.create_index(
        op.f("ix_account_user_username"), "account_user", ["username"], unique=True
    )
    op.create_table(
        "account_user_role_link",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["account_role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account_user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "agent",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "version", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "logo_url", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("is_acp_support", sa.Boolean(), nullable=False),
        sa.Column(
            "acp_url", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("is_a2a_support", sa.Boolean(), nullable=False),
        sa.Column(
            "a2a_url", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("is_anp_support", sa.Boolean(), nullable=False),
        sa.Column(
            "anp_url", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "approval_status",
            sa.Enum("DRAFT", "PENDING", "APPROVED", "REJECTED", name="approvalstatus"),
            nullable=False,
        ),
        sa.Column("processed_by_id", sa.Uuid(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "process_comments",
            sqlmodel.sql.sqltypes.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column("vector_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["account_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["processed_by_id"],
            ["account_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_id"), "agent", ["id"], unique=False)
    op.create_index(op.f("ix_agent_name"), "agent", ["name"], unique=False)
    op.create_index(op.f("ix_agent_version"), "agent", ["version"], unique=False)
    op.create_index(
        "uq_agent_name_version_active",
        "agent",
        ["name", "version"],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_agent_name_version_active",
        table_name="agent",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_index(op.f("ix_agent_version"), table_name="agent")
    op.drop_index(op.f("ix_agent_name"), table_name="agent")
    op.drop_index(op.f("ix_agent_id"), table_name="agent")
    op.drop_table("agent")
    op.drop_table("account_user_role_link")
    op.drop_index(op.f("ix_account_user_username"), table_name="account_user")
    op.drop_index(op.f("ix_account_user_phone"), table_name="account_user")
    op.drop_index(op.f("ix_account_user_id"), table_name="account_user")
    op.drop_index(op.f("ix_account_user_email"), table_name="account_user")
    op.drop_table("account_user")
    op.drop_index(op.f("ix_account_role_name"), table_name="account_role")
    op.drop_index(op.f("ix_account_role_id"), table_name="account_role")
    op.drop_table("account_role")
    # ### end Alembic commands ###
